-- 코드를 작성해주세요
# SELECT  substring(YM,1,4) AS YEAR, 
#         SUM(PM_VAL1) AS PM10, 
#         SUM(PM_VAL2) AS PM2.5
# FROM AIR_POLLUTION 
# WHERE LOCATION2 IN '수원';

SELECT YEAR(YM) AS YEAR, 
    ROUND(AVG(PM_VAL1),2) AS PM10, 
    ROUND(AVG(PM_VAL2),2) AS 'PM2.5'
FROM AIR_POLLUTION 
WHERE LOCATION2 = '수원' 
GROUP BY YEAR(YM) 
ORDER BY YEAR(YM) ASC