-- 코드를 작성해주세요
-- PARENT_ITEM_ID 는 업그레이드 전 단계의 ITEM_ID
WITH T1 AS 
(SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY, A.PRICE, B.PARENT_ITEM_ID
FROM ITEM_INFO A
INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = 'RARE'
)
SELECT C.ITEM_ID, D.ITEM_NAME, D.RARITY
FROM T1 T
INNER JOIN ITEM_TREE C ON T.ITEM_ID = C.PARENT_ITEM_ID
INNER JOIN ITEM_INFO D ON C.ITEM_ID = D.ITEM_ID 
ORDER BY C.ITEM_ID DESC