-- 코드를 작성해주세요
-- 2(2) 2(3) 2(5) 2(6) 2(9)
SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID ASC